[TIMETABLE-101]: Docker-compose
ArsenOOO7/timetable-microservice pull request #105
Opened 2023-09-02 14:54 UTC by JJerome-NM

2023-09-05 17:04 UTC, ArsenOOO7 requested changes

2023-09-08 11:48 UTC, JJerome-NM commented on docker-compose.yml
> +  rabbitmq_db:
I think it can be removed

2023-09-08 11:48 UTC, JJerome-NM commented on docker-compose.yml
> +      - target: 9200
Changed

2023-09-29 08:00 UTC, ArsenOOO7 approved these changes

2023-09-29 08:01 UTC, merged