[TIMETABLE-128] Added profiles
ArsenOOO7/timetable-microservice pull request #131
Opened 2024-07-22 14:35 UTC by JJerome-NM

2024-08-01 19:42 UTC, ArsenOOO7 commented on timetable-config/src/main/resources/application.yml
> +    active: ${TIMETABLE_ACTIVE_PROFILE:local, native}
native?

2024-08-01 19:43 UTC, ArsenOOO7 requested changes
question

2024-08-05 11:27 UTC, JJerome-NM commented on timetable-config/src/main/resources/application.yml
> +    active: ${TIMETABLE_ACTIVE_PROFILE:local, native}
Without "native" exception)
![image](https://github.com/user-attachments/assets/4960092d-a1bb-4646-9dc8-837db1e06dfb)

2024-08-05 14:49 UTC, ArsenOOO7 commented on timetable-config/src/main/resources/application.yml
> +    active: ${TIMETABLE_ACTIVE_PROFILE:local, native}
uhm, ok

2024-08-05 14:50 UTC, ArsenOOO7 approved these changes

2024-08-06 11:49 UTC, merged